### ISSUE TITLE
Text metrics

### ISSUE THREAD

**Issue by deviator** [AuburnSounds/printed#13]
I think base render api must provide functions for getting metrics of text with selected style (font, size etc) like a width and height of string (may be more metrics).

FreeType provides `width`, `height`, `horiBearingX`, `horiBearingY`, `horiAdvance`, `vertBearingX`, `vertBearingY`, `vertAdvance` about glyph.
https://www.freetype.org/freetype2/docs/tutorial/step2.html

It's useful for develop highlevel libraries for example for rendering TeX formulas, tables with text and etc.

**Comment by p0nce** [comment]
Yes indeed the rendering context should give back text metrics.
We should look at the Canvas API not FreeType imo, since PDF and SVG use the right bearing, horizontal advance between characters, also it would be inneficient to feed character by character instead of at least word by word.

**Comment by deviator** [comment]
I agree, I used feed by glyph as an example only.

**Comment by p0nce** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics

**Comment by p0nce** [comment]
Depends on  #16

**Comment by p0nce** [comment]
Implemented width aka advance, further work depends on #17

**Comment by p0nce** [comment]
https://www.cairographics.org/manual/cairo-cairo-scaled-font-t.html#cairo-text-extents-t

**Comment by p0nce** [comment]
For flow layout we need both `horiAdvance` and `width`.

**Comment by p0nce** [comment]
Fixed, though some values aren't good.
