### ISSUE TITLE
Non-optional dependency printed:image of printed not found in dependency tree

### ISSUE THREAD

**Issue by dkorpel** [AuburnSounds/printed#20]
When trying to build my dub project depending on this package (0.0.9) , I get the error:
```
Non-optional dependency printed:image of printed not found in dependency tree!?.
```
Looking at the package format, I see:
```
    "dependencies":
    {
        "printed:canvas": "*",
        "printed:font": "*",
        "printed:image": "*"
},
```
But the sub-packages are named `font`, `canvas` and *`htmlcolors`*, not `image`. Is the package description incorrect or am I doing something wrong?

**Comment by p0nce** [comment]
Hello, try  v0.0.10 when it's on the registry!

**Comment by dkorpel** [comment]
Thanks for the quick fix!

**Comment by p0nce** [comment]
My pleasure! Thanks for submitting the issue
