### ISSUE TITLE
Invalid source/import path: `printed-1.0.1/printed/source`

### ISSUE THREAD

**Issue by a-ludi** [AuburnSounds/printed#27]
When importing the `printed` package into the project the DUB (or the compiler?) issues a warning that the source path is invalid. I think it originates from splitting the package into several sub-packages and should be pretty easy to fix by clearing these paths in `dub.json`: `"importPaths": [], "sourcePaths": []`

**Comment by p0nce** [comment]
do like the examples and use `"printed:canvas"` as the dependency

**Comment by a-ludi** [comment]
Yes, I did that. Still, it should be fixed, IMHO.
