### ISSUE TITLE
save/restore is broken in SVG

### ISSUE THREAD

**Issue by a-ludi** [AuburnSounds/printed#28]
The current implementation of [`SVGDocument.restore()`](https://github.com/AuburnSounds/printed/blob/bbfa8697eaf756562948ca654d9c4feeded010b1/canvas/printed/canvas/svgrender.d#L71) pops the entire stack but all other operations on the stack just push a single element/group onto it.

I am irritated by this behavior and would expect that it pops all elements until the level that `save()` was called is reached. Is the current behavior intended? I am no PDF expert but to me it looks like the `PDFDocument` has a different implementation that acts more like my expectation.

Here is an example of what I would like to do: Draw several objects into a "content area" of the page which is the page minus some padding on all sides. I would try to do it like this:

```d
enum paddingTop = 42f;
enum paddingLeft = 42f;

renderer.translate(paddingLeft, paddingTop);
renderer.save();

// plot object1
// plot object2
// ...

renderer.restore();
```

But if I use the `save/restore` pattern inside one of the objects, the rest will not be transformed by the initial translate.

**Comment by p0nce** [comment]
For SVG this does look buggy.
`save()` should push in a real stack the current number of opened `<g>` (they are opened by `scale`/`translate`/`rotate` mostly) and eventually needed state, and `restore` should only close with `</g>` up to that last, saved point.

**Comment by p0nce** [comment]
Fixed in v1.0.3

**Comment by p0nce** [comment]
Thanks for reporting !

**Comment by a-ludi** [comment]
Great, thanks!
