### ISSUE TITLE
`SVGDocument.strokeRect` ignores `lineWidth`

### ISSUE THREAD

**Issue by a-ludi** [AuburnSounds/printed#29]
[`SVGDocument.strokeRect`](https://github.com/AuburnSounds/printed/blob/bbfa8697eaf756562948ca654d9c4feeded010b1/canvas/printed/canvas/svgrender.d#L106) ignores the `lineWidth` but it should set the `stroke-width` attribute of the `<rect>` element accordingly.

**Comment by p0nce** [comment]
Fixed in v1.0.2
